---
platform: linux

image_resource:
    type: docker-image
    source: {repository: ubuntu}

inputs:
    - name: build-scripts

outputs:
    - name: artifacts
    
run:
    path: sh
    args: ["echo ceva"]
