resource_types:
- name: samba-resource
  type: docker-image
  source:
    repository: papagalu/test-resource

resources:
- name: test-resource
  type: samba-resource
  source:
    samba_share: <samba share>
    folder: orice
    password: Passw0rd
- name: build-scripts
  type: git
  source:
    uri: https://github.com/mbivolan/lis-pipeline.git
    branch: container-build
- name: build-yml
  type: git
  source:
    uri: https://github.com/mbivolan/concourse.git
    branch: master

jobs:
- name: build-kernel
  plan:
  - get: build-scripts
  - get: build-yml
  - task: build deb
    file: build-yml/pipelines/tasks/build-deb.yml
    params:
      KERNEL_PATH: https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.13.9.tar.xz
  - put: test-resource
